siteTitle = 'Trà Sữa Mai Ngốc Nghếch'
siteDescr = 'Tận hưởng niềm vui cùng Mai Ngốc Nghếch'
siteDescription = "Uống trà sữa, dạo chơi trên bờ biển cát trắng tại đâu cũng được quan trọng gì đâu"
siteUrl = "http://ngoibuongodaimotcaiten.com"
siteBandcampUrl = 'https://ngoibuongodaimotcaiten.com'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/vivuhotel'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/nihon_ne'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/nihonne'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
